In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("C:/Users/chand/OneDrive/Documents/Python ihub/used_cars_messy.csv")

Task 1 Data cleaning

In [5]:
print("Missing values :\n", df.isnull().sum())

Missing values :
 Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [10]:
df.shape

(15661, 14)

In [11]:
df.fillna(df.median(numeric_only = True), inplace = True)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,88.50,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,1248.0,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [12]:
for col in df.select_dtypes(include = 'object'):
    df[col].fillna(df[col].mode()[0], inplace = True)

C:\Users\chand\AppData\Local\Temp\ipykernel_12168\1321033635.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include = 'object'):
C:\Users\chand\AppData\Local\Temp\ipykernel_12168\1321033635.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace = True)

In [13]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine                  0
max_power               0
seats                   0
selling_price           0
dtype: int64

In [14]:
df = df.drop_duplicates()

In [15]:
df.shape

(15492, 14)

Task 2 Preprocessing

In [16]:
# One hot encoding
df = pd.get_dummies(df, drop_first = True)

In [17]:
x = df.drop("selling_price" ,axis = 1)
y = df["selling_price"]

In [18]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [19]:
scalar = StandardScaler()

In [22]:
x_train = scalar.fit_transform(x_train)

In [23]:
x_test = scalar.transform(x_test)

In [24]:
df

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price,car_name_Audi A6,car_name_Audi A8,car_name_Audi Q7,car_name_BMW 3,...,mileage_8.5,mileage_8.6,mileage_8.77,mileage_8.9,mileage_9.17,mileage_9.26,mileage_9.3,mileage_9.5,mileage_9.5 kmpl,mileage_9.52
0,2581,7,1461.0,83.80,5.0,575000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,224,3,998.0,67.04,5.0,435000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1803,3,1497.0,117.60,5.0,875000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2728,6,2179.0,88.50,8.0,925000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,14160,4,2179.0,140.00,7.0,1175000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,7,1248.0,88.80,7.0,665000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15657,17029,11,1248.0,103.20,5.0,249000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15658,6839,7,998.0,67.04,5.0,250000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15659,1104,2,1197.0,81.86,5.0,620000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15660,9295,2,1462.0,103.25,5.0,960000.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False